spring.application.name=SyncDesk
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# ? DATABASE CONFIGURATION (ADD THIS)
spring.datasource.url=jdbc:postgresql://localhost:5432/syncdesk
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Server
server.port=8080