spring.application.name=SyncDesk
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# ? DATABASE CONFIGURATION (ADD THIS)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/syncdesk}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Server
server.port=8080

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}


# 1. Maximum number of connections in the pool
# For a 1GB RAM VM, 2-4 is plenty.
spring.datasource.hikari.maximum-pool-size=3

# 2. How long a connection can sit idle before being closed
spring.datasource.hikari.idle-timeout=30000

# 3. Minimum number of connections to keep open
spring.datasource.hikari.minimum-idle=1

# 4. Maximum time to wait for a connection from the pool
spring.datasource.hikari.connection-timeout=20000

# 5. Max lifetime of a connection (Neon recommends keeping this under 30 mins)
spring.datasource.hikari.max-lifetime=1800000
